

version: '3.8'

services:
  dns-server:
    build: ./dns
    container_name: dns-server
    ports:
      - "192.168.2.151:53:53/udp"
      - "192.168.2.151:53:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      tracevia-net:
        ipv4_address: 172.25.0.53

  front:
    dns: [172.25.0.53]
    build:
      context: ./ligador-wifi
      dockerfile: Dockerfile
    image: wifi-frontend
    restart: always
    ports:
      - "4205:4205"
    environment:
      FRONT_ENV: teste
    networks:
      - tracevia-net

  back:
    dns: [172.25.0.53]
    build:
      context: ./target/0.0.2
      dockerfile: Dockerfile
    image: wifi-backend:0.0.2-SNAPSHOT
    env_file:
      - .env
    ports:
      - "8085:8085"
    restart: always
    environment:
      - ASTERISK_HOST=asterisk
      - ASTERISK_PORT=5038
    depends_on:
      - asterisk
    networks:
      - tracevia-net

  nginx:
    dns: [172.25.0.53]
    build: ./nginx
    image: wifi-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - asterisk
    volumes:
      - /home/tracevia/app/certificates/homologacaotracevia.com.br-0003/:/etc/nginx/certs/:ro
      - /home/tracevia/app/applications/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - tracevia-net

  asterisk:
    dns: [172.25.0.53]
    image: asterisk/asterisk:18.11.0
    container_name: asterisk
    network_mode: host
    #ports:
      #- "5060:5060/udp"
      #- "5061:5061/tcp"
      #- "8088:8088"
      #- "8089:8089"
      #- "5038:5038/tcp"
      #- "10000-10500:10000-10500/udp"
    #networks:
      #
      #- tracevia-net
    volumes:
      - ./asterisk/config/:/etc/asterisk/:ro
      - /home/tracevia/app/certificates/homologacaotracevia.com.br-0003/:/etc/asterisk/keys/:ro
      - asterisk-data:/var/lib/asterisk
      - asterisk-logs:/var/log/asterisk
      - asterisk-spool:/var/spool/asterisk
    environment:
      - TZ=America/Sao_Paulo
    restart: always

networks:
  tracevia-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16  # 🔥 Mudado para evitar conflito

volumes:
  asterisk-data:
  asterisk-logs:
  asterisk-spool:

